### ISSUE TITLE
Centered shadow can't be customized

### ISSUE THREAD

**Issue by gabrielaraujof** [gabrielaraujof/shadow-science#7]
When not setting a specific position the other settings are ignored.

In this example, both key and ambient lights are applied:
```html
<article shadow-sci shadow-sci-source="key-light-only">
    <p>At the center.</p>
</article>
```
In this case, the state is ignored as well:
```html
<article shadow-sci shadow-sci-state="raised" shadow-sci-source="key-light-only">
  <p>At the center.</p>
</article>
```

**Comment by vromao** [comment]
You right! I forgot to add the shadows variations in default class too, hahaha. Beside that I took the chance to improve code avoiding redundancy. PR to resolve this issue above.
